### PR TITLE
Add into_ref(self) -> &'a T for InternArena<'a, T>

### PR DESCRIPTION
**Pull request by ThePuzzlemaker**
This allows you to store arena-interned values into structures inline (i.e. without `&'a InternArena<'a, T>`, which is just wasteful), and still be able to borrow the values inside of the interned value without providing a reference itself. For example:
```rs
struct Bar {
    baz: String,
}

struct Foo<'a>(InternArena<'a, Bar>);

impl<'a> Foo<'a> {
    pub fn get_baz(self) -> &'a str {
        self.0.into_ref().baz
    }
}
```

Without this addition, doing this requires a `&self` in order for the borrow checker to be satisfied, which to be honest is wasteful, when this type can be `Copy` anyway. This is especially useful when using wrapper types to enforce API boundaries.

The reason why this cannot be done with `Deref` or `AsRef` is because both of those traits require a `&self` receiver, which means you have to locally borrow `self.0`, which makes the borrow checker now think you are returning borrowed data from data owned in the function, even though you are not.

### CODE REVIEW

**Comment by droundy** [comment]
Looks like a nice improvement, but needs a doc comment explaining how you would use it as you did in f the pull request. I'd love to see the doc also having an example using it.

**Comment by ThePuzzlemaker** [comment]
@droundy Finally got around to this, kinda got lost in my backlog :sweat_smile:

**Comment by ThePuzzlemaker** [comment]
Ah, pedantry :P

**Comment by SandaruKasa** [comment]
Would love to see this merged!

**Comment by droundy** [comment]
Thanks for the mention. In my defense regarding getting this reviewed, I have a 13 month old daughter.

**Comment by SandaruKasa** [comment]
> Thanks for the mention. In my defense regarding getting this reviewed, I have a 13 month old daughter.

Oh, wow. Congratulations to you!

**Pull request merged**
